#!/bin/bash
#!
#! Copyright (C) 2010-2013 Andrea Dal Corso 
#! This file is distributed under the terms of the
#! GNU General Public License. See the file `License'
#! in the root directory of the present distribution,
#! or http://www.gnu.org/copyleft/gpl.txt .
#!

. ../QE_path
element='all'

# do not change after this line. Uncomment the appropriate line if
# you want to test the additional PPs or to use a version of 
# QE < 5.0 (at your own risk).

work=./WORK
#  For QE < 5.0 
#. $PWDIR/example/environment_variables
#
. $PWDIR/environment_variables
BIN_DIR=$PWDIR/bin

rm -rf *.in
rm -rf WORK
rm -rf $2
mkdir $work >& /dev/null
mkdir $2 >& /dev/null


function check {
   # 检查上一个命令的退出状态码
   if [ $? -ne 0 ]; then
      echo "任务异常：$1"
   fi
}


#!/bin/bash

variable="a"

case $2 in
    "PAW_HIGH")
        echo "$1: $2"
        . ../paw_ps_high.job
        ;;
    "PAW_LOW")
        echo "$1: $2"
        . ../paw_ps_low.job
        ;;
    "US_HIGH")
        echo "$1: $2"
        . ../us_ps_high.job
        ;;
    "US_LOW")
        echo "$1: $2"
        . ../us_ps_low.job
        ;;
    "NC")
        echo "$1: $2"
        . ../nc_ps_collection.job
        ;;
    "*")
        echo "暂不支持生成此类型的赝势$2"
        ;;
esac

#
#   These two files generate PAW and US PPs for all elements. These are
#   high accuracy - high kinetic energy cut-off PPs.
#


#
#   These two files generate additional PAW and US PPs for some elements. 
#   These are less accurate PP than the previous one but require
#   lower kinetic energy cut-off or have less projectors or less semicore
#   states.
#



#  Uncomment the following line to generate the old pslibrary 0.3.1 PPs. 
#
#. ../paw_ps_collection.job
#. ../us_ps_collection.job

#  Uncomment the following line to generate the NC-PPs. Be very careful
#  these PPs are completely untested.
#


#  Uncomment the following line to generate additional PAW data sets. Be
#  careful these PPs might have problems.
#
#. ../paw_ps_collection_tot.job

#  Uncomment the following line to generate additional PAW data sets. 
#  These are alternative data sets. 
#
#. ../paw_ps_collection_alt.job

#  Old PP files for Lanthanides. 
#  Require an atomic code with svn version older than 10324.
#  This file is obsolete. The PPs have been moved to paw_ps_low and corrected.
#
#. ../paw_lan_collection.job

#  Uncomment the following line to generate additional US-PPs. Be
#  careful these PPs might have problems.
#
#. ../us_ps_collection_tot.job

#  Uncomment the following line to generate additional US-PPs. 
#  These are alternative PPs
#
#. ../us_ps_collection_alt.job

#  Old PP files for Lanthanides.  
#  Require an atomic code with svn version older than 10324.
#  This file is obsolete. The PPs have been moved to us_ps_low and corrected.
#
#. ../us_lan_collection.job

ld1_command="$PARA_PREFIX $BIN_DIR/ld1.x $PARA_POSTFIX"

# echo "ld1_command =" $ld1_command

for elem in $element ; do
    if [ $elem = "all" ] ;
    then

       for atom in *.in ; do
         #  echo -e "Making   $atom  ...\c"
          $ld1_command < ./$atom > $work/$atom.out > /dev/null 2>&1
          check $atom.out
       done

    else

       for atom in "$elem"*.in ; do
         #   echo -e "Making   $atom  ...\c"
           $ld1_command < ./$atom > $work/$atom.out > /dev/null 2>&1
           check $atom.out
       done

    fi
done

\mv *.UPF $2
# \mv *.in WORK
\rm -rf *.in
\rm -rf WORK